---
title: "Technology Exploration of new R Packages"
---
For this section, I have explored the creative use of R packages to visualise data from the same SQL query in three different ways. 

It Includes:

-   **Plotly:** Interactive Visualisation
-   **Rayshader:** 3D Rendering
-   **Tidymodels:** Using Machine Learning

```{r}
#| label: Install and Load Libraries
#| message: true
#| warning: true
#| include: false

# Install packages, load libraries
if(!require("tidyverse"))
  install.packages("tidyverse")
  library(tidyverse)

if(!require("DBI"))
  install.packages("DBI")
  library(DBI)

if(!require("RSQLite"))
  install.packages("RSQLite")
  library(RSQLite)

if(!require("DT"))
  install.packages("DT")
  library(DT)

if(!require("dplyr"))
  install.packages("dplyr")
  library(dplyr)

if(!require("ggplot2"))
  install.packages("ggplot2")
  library(ggplot2)

if(!require("plotly"))
  install.packages("plotly")
  library(plotly)

if(!require("tidymodels"))
  install.packages("tidymodels")
  library(tidymodels)

if(!require("rayshader"))
  install.packages("rayshader")
  library(rayshader)

if(!require("rgl"))
  install.packages("rgl")
  library(rgl)

# Connect to database
conn <- dbConnect(RSQLite::SQLite(), "virtual_production.db")

```

```{r}
#| label: Run Query 
#| message: true
#| warning: true
#| include: false

# Queries the database and runs part1
data <- dbGetQuery(conn, "SELECT Productions.ProductionID, Productions.Title, Productions.Budget, COUNT(DISTINCT ProductionCrew.CrewID) AS CrewSize, Productions.Status FROM Productions LEFT JOIN ProductionCrew ON Productions.ProductionID = ProductionCrew.ProductionID GROUP BY Productions.ProductionID, Productions.Title, Productions.Budget, Productions.Status;")

# Queries the database and runs part1
data <- data %>% mutate(SuccessRate = case_when(Status == "Completed" ~ 1, Status == "In Progress" ~ 0.5, TRUE ~ 0))

```

#Interactive Visualisation with Plotly

```{r}

# Queries the database and runs part1
p <- ggplot(data, aes(x = Budget, y = SuccessRate, size = CrewSize, colour = Status, text = Title)) + geom_point(alpha = 0.7) + labs(title = "Budget vs SuccessRate (Interactive Plotly)") + theme_minimal()

# Queries the database and runs part1
ggplotly(p, tooltip = c("text", "x", "y"))

```

#3D Rendering with Rayshader

```{r}

# Queries the database and runs part1
p <- ggplot(data, aes(x = Budget, y = SuccessRate, size = CrewSize, colour = Status, text = Title)) + geom_point(alpha = 0.7) + labs(title = "Budget vs SuccessRate (Interactive Plotly)") + theme_minimal()

# Queries the database and runs part1
ggplotly(p, tooltip = c("text", "x", "y"))

```