---
title: "SQL Queries and Database Exploration"
format: html
---

```{r}
#| label: Libraries and DB Connection
#| message: true
#| warning: true

# Install packages, load libraries
if(!require("tidyverse"))
  install.packages("tidyverse")
  library(tidyverse)

if(!require("DBI"))
  install.packages("DBI")
  library(DBI)

if(!require("RSQLite"))
  install.packages("RSQLite")
  library(RSQLite)

if(!require("kableExtra"))
  install.packages("kableExtra")
  library(kableExtra)

if(!require("DT"))
  install.packages("DT")
  library(DT)

# Connect to database
conn <- dbConnect(RSQLite::SQLite(), "virtual_production.db")

# Display database tables
dbListTables(conn)
```

```{r}
#| label: Part 1
#| message: true
#| warning: true
#| paged-print: true

# Takes the country field from Clients table & counts how many productions exist for each country and adds all budgets of productions of clients in the country
# Sets Productions as main table that we are pulling data from and assign it the value "p"
# Connect the two tables
# Group by country
# Order by total budget in descending order

part1 <- "SELECT c.Country, COUNT(p.ProductionID) AS ProjectCount, SUM(p.Budget) AS TotalBudget FROM Productions p JOIN Clients c ON p.ClientID = c.ClientID GROUP BY c.Country ORDER BY TotalBudget DESC;"

# Queries the database and runs part1
result1 <- dbGetQuery(conn, part1)

# Adds results to a table
head(result1)

# Display Table with results
kable(result1, caption = 'Total Budget and Project Count per Country') %>% kable_styling(full_width = FALSE, position = "center", bootstrap_options = c("striped", "hover"))

```

```{r}
#| label: Part 2
#| message: true
#| warning: true
#| paged-print: true

# Takes the country field from Clients table & counts how many productions exist for each country and adds all budgets of productions of clients in the country
# Sets Productions as main table that we are pulling data from and assign it the value "p"
# Connect the two tables
# Group by country
# Order by total budget in descending order

part2 <- "WITH AssetCount AS ( SELECT Environments.ProductionID, COUNT(Assets.AssetID) AS NumAssets FROM Environments JOIN Assets ON Environments.EnvironmentID = Assets.EnvironmentID GROUP BY Environments.ProductionID), ProductionTime AS ( SELECT ProductionID, JULIANDAY(EndDate) - JULIANDAY(StartDate) AS DurationDays FROM Productions ) SELECT AssetCount.NumAssets, ROUND(AVG(ProductionTime.DurationDays), 2) AS AvgDevelopmentDays FROM AssetCount JOIN ProductionTime ON AssetCount.ProductionID = ProductionTime.ProductionID GROUP BY AssetCount.NumAssets ORDER BY AssetCount.NumAssets;"

# Queries the database and runs part1
result2 <- dbGetQuery(conn, part2)


# Display Table with results
datatable(result2, caption = "Average Development Time by Number of Assets", options = list(pageLength = 8))

```

```{r}
#| label: Part 3
#| message: true
#| warning: true
#| paged-print: true

# Takes the country field from Clients table & counts how many productions exist for each country and adds all budgets of productions of clients in the country
# Sets Productions as main table that we are pulling data from and assign it the value "p"
# Connect the two tables
# Group by country
# Order by total budget in descending order

part3 <- "SELECT CrewMembers.Name AS CrewMember, COUNT(DISTINCT ProductionCrew.ProductionID) AS SuccessfulProductions FROM CrewMembers JOIN ProductionCrew ON CrewMembers.CrewID = ProductionCrew.CrewID JOIN Productions ON Productions.ProductionID = ProductionCrew.ProductionID Where Productions.Status = 'Completed' GROUP BY CrewMembers.Name ORDER BY SuccessfulProductions DESC LIMIT 3;"

# Queries the database and runs part1
result3 <- dbGetQuery(conn, part3)


# Display Table with results
kable(result3, caption = "Top Three Crew Members by Successful Productions") %>% kable_styling(full_width = FALSE, position = 'center', bootstrap_options = c('striped', 'hover'))

```

# General SQL Concepts Demonstration

### SQL Concept 1 Demonstration

```{r}
#| label: SQL Concepts Part 1
#| message: true
#| warning: true
#| paged-print: true

sqlconcept1 <- "SELECT Clients.ClientName, Clients.Country, Productions.Title, Productions.Genre FROM Clients JOIN Productions ON Clients.ClientID = Productions.ClientID WHERE (Clients.Country LIKE '%UK%' OR Clients.Country LIKE '%Japan%') AND (Productions.Genre LIKE '%Sci-Fi%' or Productions.Genre LIKE '%Drama%') ORDER BY CLients.Country, Productions.Title;"

# Queries the database and runs SQL concept demonstration 1
result4 <- dbGetQuery(conn, sqlconcept1)

# Display Table with results
kable(result4, caption = 'Productions for Clients in UK or USA with Action or Drama Genres') %>% kable_styling(full_width = FALSE, position = 'center')
```


### SQL Concept 2 Demonstration

```{r}
#| label: SQL Concepts Part 2
#| message: true
#| warning: true
#| paged-print: true

sqlconcept2 <- "SELECT Clients.ClientName, Clients.Country, Productions.Title, Productions.Genre FROM Clients JOIN Productions ON Clients.ClientID = Productions.ClientID WHERE (Clients.Country LIKE '%UK%' OR Clients.Country LIKE '%Japan%') AND (Productions.Genre LIKE '%Sci-Fi%' or Productions.Genre LIKE '%Drama%') ORDER BY CLients.Country, Productions.Title;"

# Queries the database and runs SQL concept demonstration 1
result4 <- dbGetQuery(conn, sqlconcept2)

# Display Table with results
kable(result4, caption = 'Productions for Clients in UK or USA with Action or Drama Genres') %>% kable_styling(full_width = FALSE, position = 'center')
```

```{r}
#| label: SQL Concepts Part 3
#| message: true
#| warning: true
#| paged-print: true

sqlconcept3 <- "SELECT Clients.ClientName, Clients.Country, Productions.Title, Productions.Genre FROM Clients JOIN Productions ON Clients.ClientID = Productions.ClientID WHERE (Clients.Country LIKE '%UK%' OR Clients.Country LIKE '%Japan%') AND (Productions.Genre LIKE '%Sci-Fi%' or Productions.Genre LIKE '%Drama%') ORDER BY CLients.Country, Productions.Title;"

# Queries the database and runs SQL concept demonstration 1
result4 <- dbGetQuery(conn, sqlconcept3)

# Display Table with results
kable(result4, caption = 'Productions for Clients in UK or USA with Action or Drama Genres') %>% kable_styling(full_width = FALSE, position = 'center')
```